"""remove_socialapp_id_field_from_user_table

Revision ID: 046e05863aaa
Revises: abfdbc1bc8ca
Create Date: 2018-05-21 18:22:12.661137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '046e05863aaa'
down_revision = 'abfdbc1bc8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'socialapp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('socialapp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('user_ibfk_1', 'user', 'socialapp', ['socialapp_id'], ['id'])
    # ### end Alembic commands ###
