"""user_role_relationship

Revision ID: 4a8c2aef1c11
Revises: cf8d1fde8567
Create Date: 2018-05-21 09:51:55.650115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a8c2aef1c11'
down_revision = 'cf8d1fde8567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_ibfk_1', 'role', type_='foreignkey')
    op.drop_column('role', 'user_id')
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'role', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_id')
    op.add_column('role', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('role_ibfk_1', 'role', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
