"""role_id_field_name_fixed

Revision ID: 7a5cf9bda4b6
Revises: 4a8c2aef1c11
Create Date: 2018-05-21 09:58:52.177045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a5cf9bda4b6'
down_revision = '4a8c2aef1c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_ibfk_2', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_2', 'user', 'role', ['user_id'], ['id'])
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###
