"""user tables

Revision ID: 8b2e967b61b7
Revises: f53a66db2eab
Create Date: 2018-05-21 09:14:12.868508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2e967b61b7'
down_revision = 'f53a66db2eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=False),
    sa.Column('socialapp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['socialapp_id'], ['socialapp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('socialtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socialtoken')
    op.drop_table('user')
    # ### end Alembic commands ###
