"""permissions pack tables

Revision ID: aa2120371875
Revises: 7a5cf9bda4b6
Create Date: 2018-05-21 10:07:44.178570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2120371875'
down_revision = '7a5cf9bda4b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permpack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permpack_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permpack_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['permpack_id'], ['permpack.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permpack_id', 'operation_id', name='UT_permpack_operation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permpack_operation')
    op.drop_table('permpack')
    # ### end Alembic commands ###
