"""move_socialapp_id_field_to_role_table

Revision ID: abfdbc1bc8ca
Revises: c8ec6c3e0091
Create Date: 2018-05-21 18:17:18.646749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abfdbc1bc8ca'
down_revision = 'c8ec6c3e0091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('socialapp_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'role', 'socialapp', ['socialapp_id'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'socialapp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('socialapp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('user_ibfk_1', 'user', 'socialapp', ['socialapp_id'], ['id'])
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'socialapp_id')
    # ### end Alembic commands ###
