"""socialapp_unique_constrains

Revision ID: c8ec6c3e0091
Revises: 6ab2b34ac08c
Create Date: 2018-05-21 12:45:10.836832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8ec6c3e0091'
down_revision = '6ab2b34ac08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialapp', sa.Column('secret_key', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'socialapp', ['secret_key'])
    op.create_unique_constraint(None, 'socialapp', ['client_id'])
    op.drop_column('socialapp', 'secret_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialapp', sa.Column('secret_id', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'socialapp', type_='unique')
    op.drop_constraint(None, 'socialapp', type_='unique')
    op.drop_column('socialapp', 'secret_key')
    # ### end Alembic commands ###
