"""add_socialapp_id_field_to_role_table

Revision ID: f760be0a0e5d
Revises: ff23895b1cd7
Create Date: 2018-05-21 15:00:48.811010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f760be0a0e5d'
down_revision = 'ff23895b1cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('socialapp_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'role', 'socialapp', ['socialapp_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'socialapp_id')
    # ### end Alembic commands ###
