"""add_socialapp_id_field_to_permpack_table

Revision ID: fcac40272e15
Revises: abfdbc1bc8ca
Create Date: 2018-05-22 07:28:36.567667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcac40272e15'
down_revision = 'abfdbc1bc8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permpack', sa.Column('socialapp_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'permpack', 'socialapp', ['socialapp_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permpack', type_='foreignkey')
    op.drop_column('permpack', 'socialapp_id')
    # ### end Alembic commands ###
