"""remove_socialapp_id_field_from_user_table

Revision ID: ff23895b1cd7
Revises: c8ec6c3e0091
Create Date: 2018-05-21 15:00:11.443468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff23895b1cd7'
down_revision = 'c8ec6c3e0091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'socialapp_id')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'socialapp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('socialapp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('user_ibfk_1', 'user', 'socialapp', ['socialapp_id'], ['id'])
    op.add_column('role', sa.Column('socialapp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
